### PR TITLE
Replace cleanup with terser

### PR DESCRIPTION
**Pull request by moonglum**
This is a proposal to add (optional) stronger compaction with terser: [terser](https://github.com/terser-js/terser) is a fork of UglifyJS that supports ES6 and beyond. terser basically has three levels of compaction: It always reduces whitespace. It can also mangle (mangle means replacing variable names with short variable names) and compress (this applies a set of more complex transformations). [Deactivating compress is described as the 'fast minify mode' in the README](https://github.com/terser-js/terser#terser-fast-minify-mode). The reduction in gzip size is still really good: From the comparison table they provide, that level is not worth it. It takes a long time with very little gain. It also has quite some risk associated with it in my opinion and complicates the mapping between the written and uglified code further. So we don't offer `compress`. The option of only reducing whitespace (without mangle and compress) is a good option, as it is really, really fast and it has the advantage that the source code stays readable: A prettifier could undo the damage we've done to the code (some browsers even offer prettifiers in their dev tools). We also keep the option to just strip comments and blank lines as offered by `rollup-plugin-cleanup`.

Open Question:
* Should `rollup-plugin-cleanup` and `rollup-plugin-terser` be optional dependencies that are loaded with `loadExtension`?

## Documentation

faucet can reduce the size of your JavaScript code. To do that, use the `--compact` CLI flag (without that flag, no compaction will be applied – this is useful for development). You configure the level of compaction on a per-bundle basis:

```js
module.exports = {
  js: [{
    source: "...",
    target: "...",
    compact: "minify"
  }]
}
```

You have the following options:

* `false`: No compaction
* `"compact"` (default): Strip comments and blank lines
* `"minify"`: Strip comments and reduce whitespace
* `"mangle"`: Strip comments, reduce whitespace and rewrite the variable names to shorter variable names

### CODE REVIEW

**Comment by moonglum** [comment]
Not sure why the build fails, it works locally...

**Comment by moonglum** [comment]
In a further enhancement, one could allow to set `compact` to either "whitespace" (the default – mangle: false, compact: false), "mangle" (mangle: true, compact: false) and "mingle-mangle" (mangle: true, compact: true). This would be similar to the compact configuration of faucet-pipeline-static, just that the default is "whitespace" and not `false`.

**Comment by FND** [comment]
Thanks for this!

However, I do not (currently?) agree that minification should _replace_ compacting (stripping comments). Of course we also don't want to overwhelm users with excessive choices...

So AIUI, with both cleanup and terser, we'd have the following options:

* no transformation (faucet: `compact: false`)
* compacting (via cleanup; mostly stripping comments and blank lines)
* minifying I (terser: `mangle: false, compact: false` - unsure what this does)
* minifying II (terser: `mangle: true, compact: false` - stripping all kinds of whitespace)
* minifying III (terser: `mangle: true, compact: true` - rewriting code; shortening identifiers etc.)

Is that correct? We could identify a straightforward set of straightforward options (e.g. none/compact/minify/extreme) to simplify the choice for users. However, that would mean faucet-core's `--compact` needs to become non-binary with a _generic_ set of choices that maps to other plugins. 

> Not sure why the build fails

Looks like minification makes the tests time out? That would suggest a performance regression (despite the "fast" claim). 🤷‍♂️

**Comment by moonglum** [comment]
I understand, and I think it's a good idea. But you got the levels wrong:

* Level 0 Nothing
* Level 1: Stripping comments and blank lines (cleanup)
* Level 2: Stripping comments and reduce whitespace (terser with mangle: false, compact: false)
* Level 3: Level 2 + shortening identifiers (terser with mangle: true, compact: false)
* Level 4: Level 3 + rewriting code (terser with mangle: true, compact: true)

(Level 2 is what you currently see in this PR)

When `--compact` is not provided, all bundles will be treated with 0. When `--compact` is provided, all packages will be treated with level 1 by default. To switch to another level per bundle, provide a `compact` option (Level 0 is `false`, for the other ones we need to find good names). Level 2 would be my recommendation to most users.

Timeout: Possible, but locally it is so fast that it's not noticeable at all. But I'll look into it.

**Comment by FND** [comment]
Thanks for the clarification.

I'll have to compare the output some other time, but I'm wondering whether there's a meaningful difference between levels 3 and 4 - if not, I'm thinking we offer four options: none / compact (level 1) / minify (level 2) / extreme (level 3 or 4). As a faucet user myself, I wouldn't wanna have to think about the minutiae of identifier shortening vs. statement rewriting every time - indeed, pondering compact vs. minify is already more pain that I'd like in my daily routine, but that distinction seems inevitable given our proclivities.

As for the CLI question, relegating detailed choices to `faucet.config.js` seems unhelpful because it would not allow for unhampered builds in development and optimized builds in production mode (at least not without inventing a whole different, proprietary mechanism, e.g. based around `process.env`).

**Comment by moonglum** [comment]
The difference between level 3 and 4:
Level 3 just renames identifiers. Nothing else. [Level 4 starts some larger code reorganization](https://github.com/terser-js/terser#compress-options) like trying to eval code beforehand, dead code elimination, hoist functions and variables etc. etc.

From the comparison table they provide, level 4 is not worth it. It takes a long time with very little gain. It also has quite some risk associated with it in my opinion and complicates the mapping between the written and uglified code further. So I suggest:

* `false`: No compaction
* `"compact"` (default): Strip comments and blank lines (cleanup)
* `"minify"`: Strip comments and reduce whitespace (terser with mangle: false, compact: false)
* `"mangle"`: Strip comments, reduce whitespace and mangle variable names (terser with mangle: true, compact: false)

**Comment by FND** [comment]
That sounds good - except I'm not sure "mangle" a) makes for a straightforward distinction for end users b) cleanly maps to other plugins (e.g. particularly non-textual sources, i.e. image optimization). Terminology seems like a solvable problem though, so I'm not too worried about this.

Does this also mean we extend faucet-core's `--compact` CLI option to optionally accept a parameter (i.e. `--compact=minify`,  `--compact=mangle`), for the reasons I'd laid out above?

**Comment by moonglum** [comment]
Sorry, forgot to address that. I think we should keep the single `--compact` CLI option (no `--compact=minify` etc.). My approach would be:

1. Choose if you want to have minification at all via the CLI
2. Choose the kind of minification per bundle in the Config

Choice 1 is mainly for the "production vs. dev" configuration. Choice 2 is your personal fine tuning for each bundle you create. For each pipeline we allow you to configure it, choosing a good default value:

1. static: No compaction by default, but you can use our image preset or go wild with your own choices
2. sass: Output of the CSS with reduced whitespace by default. No further options right now.
3. js: "compact" by default, but you can also choose other options (as outlined above).

We therefore do not need to choose compaction modes that apply to all possible pipelines, but just words that fit this pipeline.

**Comment by FND** [comment]
As discussed elsewhere, you've convinced me that specifying the respective _mechanism_ for compacting in the bundle config makes sense - despite the (small?) potential for confusion WRT requiring `--compact` to activate that mechanism in the first place. 👍

**Comment by moonglum** [comment]
@FND Ok, this works now and is ready for your review. I adjusted the PR description accordingly.

**Comment by FND** [comment]
> Should `rollup-plugin-cleanup` and `rollup-plugin-terser` be optional dependencies that are loaded with `loadExtension`?

I've been pondering this for a while: Installing rollup-plugin-terser on top of faucet-js adds 32 packages, totaling ~6 MB. That seems like a lot, so I'm inclined to say this needs to be optional.

However, I wouldn't want users to install that manually/directly, due to faucet's philosophy: We want dependencies to remain maintainable - after a while, nobody will remember what that obscure Rollup plugin is good for, but people will be hard-pressed to figure it out, thus nobody will dare remove it. That's bad. Plus it would mean that we (as faucet-js maintainers) can't easily exchange that mechanism in the future. Thus I'm afraid this would have to become another meta-package, i.e. faucet-js-minify as a simple indirection/abstraction for installing rollup-plugin-terser. WDYT?

**Comment by moonglum** [comment]
Thanks 🙇  I'm ok with the stylistic tweaks 👍 

About the dependencies:
I think we should have it as a direct dependency. Apart from the arguments brought up by you, I think there are two additional arguments:
1. If people follow our advice, they will use `--compact` only for building the production package. Let's say, they build that on CI. Locally, they will not notice the missing dependency. Only on CI. This might lead to a lot of frustration.
2. I guess that a lot of people that build JS will want to compact it. So for most people, this will be fine.

The strongest argument for me however is the one you already mentioned: The way we do compaction is an implementation detail. That's also why we don't allow to set the arguments of terser directly, but have an abstract way of referring to it. If one day [butternut](https://github.com/Rich-Harris/butternut) becomes more interesting, we want to be able to switch easily. The probability for that is much higher than switching from Babel to something else or from Rollup to something else, as this is an area with a lot more competition.

**Comment by FND** [comment]
In discussion elsewhere, we've agreed to go with a separate meta-package¹ for now. I'll take care of this (hopefully 😬 ) on my [rebased branch](https://github.com/faucet-pipeline/faucet-pipeline-js/compare/terserer).

¹ faucet-pipeline-js-compact? faucet-pipeline-compactjs?

**Comment by moonglum** [comment]
I dislike bot names, so feel free to choose the one you prefer 👍

**Comment by FND** [comment]
🤔 Are you questioning my humanity? (fair)

**Comment by FND** [comment]
Rebased, tweaked and squashed: cce62450676ef63dd8e0d3a474c6fe4d5fefc571 - thank you!

I'll leave it to you to either close or complain.

**Comment by moonglum** [comment]
Awesome! 🙇

**Pull request closed without merging**
